services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: python_app
    ports:
      - "5000:5000"
    volumes:
      - ./app:/app/app
    environment:
      - PYTHONUNBUFFERED=1
    command: gunicorn app.main:app -b 0.0.0.0:5000 --reload
